/*
how to load from tab-separated columns text file

test	factor	range	type	narrative
temperament	extravert	high	gift	You have a gift with people and are nourished by being around people. This also means that you get your life energy from being with people.

sort by type

replace single quote with &rsquo;

(.*?)\t(.*?)\t(.*?)\t(.*?)\t(.*?)\n
{ test:'$1', factor:'$2', range:'$3', narrative:'$5' },\n
*/
peg.burnouts = [
{ test:'temperament', factor:'extravert', range:'high', narrative:'Your burnout is that you will get lonely and overwhelmed if you spend too much time alone.' },
{ test:'temperament', factor:'extravert', range:'medium', narrative:'On an introvert level, you may find that you burnout with too much interaction in a large group. On an extravert level, you may find that you burnout and get lonely if spending too much time alone.' },
{ test:'temperament', factor:'extravert', range:'low', narrative:'Your burnout is that you get fatigued and overwhelmed with too much interaction in a large group.' },
{ test:'temperament', factor:'sensible', range:'high', narrative:'Your burnout is being around people who think outside the box and who don&rsquo;t follow established rules and use abstract thought processes to create solutions.' },
{ test:'temperament', factor:'sensible', range:'medium', narrative:'Your burnout is too much micromanagement and not enough definition of what is expected.' },
{ test:'temperament', factor:'sensible', range:'low', narrative:'You will be burnt out by people who only follow the rules and don&rsquo;t think for themselves, or are able two thank outside the box.' },
{ test:'temperament', factor:'thinking', range:'high', narrative:'Your burnout is being around highly emotional situations that are not rational or logical in nature.' },
{ test:'temperament', factor:'thinking', range:'low', narrative:'Your burnout is environments of rational though and objective logic.' },
{ test:'temperament', factor:'thinking', range:'medium', narrative:'Your burnout is environments of all logic and rational thought.' },
{ test:'temperament', factor:'judicious', range:'high', narrative:'Your burnout is too many simultaneous projects, unplanned events and unpredictable situations.' },
{ test:'temperament', factor:'judicious', range:'medium', narrative:'Your burnout is having too much structure or too little spontaneity.' },
{ test:'motivation', factor:'adventure', range:'high', narrative:'Your burnout is being controlled, micromanaged, details and the mundane.' },
{ test:'motivation', factor:'adventure', range:'medium', narrative:'Your burnout is having too much freedom or too little practical grounding.' },
{ test:'motivation', factor:'adventure', range:'medium', narrative:'Your burnout is having too much tradition or change.' },
{ test:'motivation', factor:'adventure', range:'low', narrative:'Your burnout is a lack tradition, chaos, lack of continuity, change and little to no structure.' },
{ test:'motivation', factor:'personal', range:'high', narrative:'Your burnout is not being publically or peer recognized for what you do.' },
{ test:'motivation', factor:'personal', range:'medium', narrative:'Your burnout may be no recognition for your work or not being able to work to your own standards and too much confrontation.' },
{ test:'motivation', factor:'personal', range:'medium', narrative:'Your burnout is no recognition or input into leadership.' },
{ test:'motivation', factor:'personal', range:'low', narrative:'Your burnout is not being recognized by your peers or superiors and publically acknowledged, and/or being valued for your input.' },
{ test:'motivation', factor:'definitions', range:'high', narrative:'Your burnout is not knowing exactly what is expected of you and the steps to follow.' },
{ test:'motivation', factor:'definitions', range:'medium', narrative:'Your burnout is either being micro-managed or not knowing what is expected of you (too much freedom in a project/position).' },
{ test:'motivation', factor:'definitions', range:'low', narrative:'Your burnout is a lack of instructions and clarity.' },
{ test:'motivation', factor:'feelings', range:'high', narrative:'Your burnout is environments of all logic and rational thought.' },
{ test:'motivation', factor:'feelings', range:'medium', narrative:'Your burnout is too much rational thought/logic or too much emotions and empathy.' },
{ test:'motivation', factor:'feelings', range:'low', narrative:'Your burnout is environments of subjective thoughts and feelings.' },
{ test:'motivation', factor:'efficiency', range:'high', narrative:'Your burnout is disorder and chaos.' },
{ test:'motivation', factor:'efficiency', range:'medium', narrative:'Your burnout is being in a position where you are detail oriented.' },
{ test:'motivation', factor:'curiosity', range:'high', narrative:'Your burnout is having a repetitive routine.' },
{ test:'motivation', factor:'curiosity', range:'medium', narrative:'Your burnout is having too much new information or being forced to learn new things in more than a moderate degree.' },
{ test:'motivation', factor:'authority', range:'high', narrative:'Your burnout is having to learn from people whom you consider non-experts.' },
{ test:'motivation', factor:'authority', range:'medium', narrative:'Your burnout is having too much adherence to established rules of society or not having any rules set by an expert authority.' },
{ test:'motivation', factor:'resistance', range:'high', narrative:'Your burnout is that you may get too far out of the context of social norms and a percentage of the population may turn on you.' },
{ test:'motivation', factor:'resistance', range:'medium', narrative:'Your burnout can be either having too many of society’s rules opposed upon you or having none of society’s rules opposed upon you.' },
{ test:'motivation', factor:'wariness', range:'high', narrative:'Your burnout is having to trust people that you do not know personally and having to disclose personal information.' },
{ test:'motivation', factor:'wariness', range:'medium', narrative:'Your burnout is being in situations where you must trust everyone regardless of your intuition.' },
{ test:'motivation', factor:'wariness', range:'low', narrative:'Your burnout is that you may be easily conned, disappointed and taken advantage of.' },
{ test:'motivation', factor:'tools', range:'high', narrative:'Your burnout is not being able to work with your hands or not being able to move.' },
{ test:'motivation', factor:'affection', range:'high', narrative:'Your burnout is not being acknowledged for what you do or not being shown affection or complimented.' },
{ test:'motivation', factor:'affection', range:'medium', narrative:'Your burnout is being shown too much affection and ignoring inner standards.' },
{ test:'motivation', factor:'acclaim', range:'high', narrative:'Your burnout is not being recognized for your work.' },
{ test:'motivation', factor:'acclaim', range:'medium', narrative:'Your burnout is being overly recognized in public and not living up to your own standards.' },
{ test:'motivation', factor:'pressure', range:'high', narrative:'Your burnout is being pushed past your ability to produce physically, emotionally or intellectually.' },
{ test:'motivation', factor:'pressure', range:'medium', narrative:'Your burnout is putting yourself under too much pressure.' },
{ test:'motivation', factor:'direct', range:'high', narrative:'Your burnout is being in a position where you are told what to do and other people make decisions for you.' },
{ test:'motivation', factor:'direct', range:'medium', narrative:'Your burnout is being in a leadership position all the time or not having a vote in the decisions being made.' },
{ test:'motivation', factor:'avoidance', range:'high', narrative:'Your burnout is a lack of boundaries and inability to stand up for yourself.' },
{ test:'motivation', factor:'avoidance', range:'medium', narrative:'Your burnout is being highly confrontational environments or where no confrontation is allowed.' },
{ test:'motivation', factor:'disappointment', range:'high', narrative:'Your burnout is blaming others for challenges and putting yourself in a victim role.' },
{ test:'motivation', factor:'disappointment', range:'low', narrative:'Your burnout is self-blame.' },
{ test:'personality', factor:'extrovert', range:'high', narrative:'Your burnout is being or working alone and no interaction with people.' },
{ test:'personality', factor:'extrovert', range:'medium', narrative:'Your burnout is being out of balance with too much social activity or too much alone time.' },
{ test:'personality', factor:'extrovert', range:'low', narrative:'Your burnout is being social or in a large group setting driven by superficial meaning.' },
{ test:'personality', factor:'independence', range:'high', narrative:'Your burnout is having to accommodate, be dependent upon others, and being tied down.' },
{ test:'personality', factor:'independence', range:'medium', narrative:'Your burnout is too much dependence on others or too much independence.' },
{ test:'personality', factor:'independence', range:'low', narrative:'Your burnout is uncooperative situations and persons where you have to be self-determined.' },
{ test:'personality', factor:'tough', range:'high', narrative:'Your burnout is ambiguity, liberal matters and an unorganized life.' },
{ test:'personality', factor:'tough', range:'medium', narrative:'Your burnout is stagnation and lack of change.' },
{ test:'personality', factor:'tough', range:'low', narrative:'Your burnout is environments of routine and set ways of thinking.' },
{ test:'personality', factor:'selfcontrol', range:'high', narrative:'Your burnout is clutter and chaos.' },
{ test:'personality', factor:'selfcontrol', range:'medium', narrative:'Your burnout is an imbalance between order/discipline and change/creativity.' },
{ test:'personality', factor:'selfcontrol', range:'low', narrative:'Your burnout is routine and controlled conventional environments.' },
{ test:'personality', factor:'anxiety', range:'high', narrative:'Your burnout is your inner pusher/driver.' },
{ test:'personality', factor:'anxiety', range:'medium', narrative:'Your burnout is trying to solve everything with your rational mind and structure and not asking for help when needed.' },
{ test:'personality', factor:'anxiety', range:'low', narrative:'Your burnout is being too relaxed to participate in solutions.' },
{ test:'personality', factor:'warm', range:'high', narrative:'Your burnout is lack of boundaries in recognizing when a person you are trying to help is not willing to help themselves, and becomes dependent on you.' },
{ test:'personality', factor:'warm', range:'medium', narrative:'Your burnout is dedicating too much of yourself to others and not maintaining your self-care.' },
{ test:'personality', factor:'warm', range:'low', narrative:'Your burnout is having to be too personal or being with people who are too personal.' },
{ test:'personality', factor:'abstract', range:'high', narrative:'Your burnout is details, concrete structured and sensible/practical environments.' },
{ test:'personality', factor:'abstract', range:'medium', narrative:'Your burnout is being too sensible/practical or too theoretical.' },
{ test:'personality', factor:'abstract', range:'low', narrative:'Your burnout is new ways of doing things and theoretical thinking.' },
{ test:'personality', factor:'stable', range:'high', narrative:'Your burnout is environments of high emotions and subjective judgements.' },
{ test:'personality', factor:'stable', range:'medium', narrative:'Your burnout is too subjective judgement.' },
{ test:'personality', factor:'stable', range:'low', narrative:'Your burnout is taking your emotions as reality.' },
{ test:'personality', factor:'dominant', range:'high', narrative:'Your burnout is being in a subordinate position.' },
{ test:'personality', factor:'dominant', range:'medium', narrative:'Your burnout is having to be in a position of being in charge all of the time and being subservient all of the time.' },
{ test:'personality', factor:'lively', range:'high', narrative:'Your burnout is social isolation.' },
{ test:'personality', factor:'lively', range:'medium', narrative:'Your burnout is likely by being too in the middle of activity and spending time alone or one on one with close friends.' },
{ test:'personality', factor:'lively', range:'low', narrative:'Your burnout is shallow conversations or gossip.' },
{ test:'personality', factor:'rule', range:'high', narrative:'Your burnout is being in situations wither there is too little rules and freedom of thought and individuality.' },
{ test:'personality', factor:'rule', range:'medium', narrative:'Your burnout is too many rules or too much freedom to interpret the rules or autonomy.' },
{ test:'personality', factor:'rule', range:'low', narrative:'Your burnout is too much adherence to strict rules.' },
{ test:'personality', factor:'bold', range:'high', narrative:'Your burnout is being socially isolated.' },
{ test:'personality', factor:'bold', range:'medium', narrative:'Your burnout is an imbalance between too much social interaction and too much privacy and autonomy.' },
{ test:'personality', factor:'bold', range:'low', narrative:'Your burnout is meeting new people with more shallow interactions and being in highly social interactions.' },
{ test:'personality', factor:'sensitive', range:'high', narrative:'Your burnout is being highly rational situations and people.' },
{ test:'personality', factor:'sensitive', range:'medium', narrative:'Your burnout is too much rational logic and too much empathy.' },
{ test:'personality', factor:'sensitive', range:'low', narrative:'Your burnout is being around feeling/sensitive subjective people and environments.' },
{ test:'personality', factor:'vigilant', range:'medium', narrative:'Your burnout is being too trusting or too suspicious' },
{ test:'personality', factor:'vigilant', range:'low', narrative:'Your burnout is that you may be taken advantage of con artists or untrustworthy people.' },
{ test:'personality', factor:'abstracted', range:'high', narrative:'Your burnout is a lack of traditional sensible practical solutions and being impractical.' },
{ test:'personality', factor:'abstracted', range:'low', narrative:'Your burnout is new creative, innovative, out of the box solutions.' },
{ test:'personality', factor:'private', range:'medium', narrative:'Your burnout is good boundaries.' },
{ test:'personality', factor:'private', range:'low', narrative:'Your burnout is that you may be taken advantage of and bold self-disclosing statements may be considered bombastic and rude by you.' },
{ test:'personality', factor:'apprehensive', range:'low', narrative:'Your burnout is that people may consider you as pompous or arrogant.' },
{ test:'personality', factor:'open', range:'high', narrative:'Your burnout is being bored with the routine or familiar tried and true methods.' },
{ test:'personality', factor:'open', range:'medium', narrative:'Your burnout is an imbalance between routine or experimentation and new ideas.' },
{ test:'personality', factor:'open', range:'low', narrative:'Your burnout is doing things that are not routine or familiar.' },
{ test:'personality', factor:'selfreliant', range:'high', narrative:'Your burnout is being dependent on others for help, decisions or survival.' },
{ test:'personality', factor:'selfreliant', range:'medium', narrative:'Your burnout is having to be too reliant on group or individual decisions or interactions.' },
{ test:'personality', factor:'selfreliant', range:'low', narrative:'Your burnout is solitary time or activities.' },
{ test:'personality', factor:'perfectionist', range:'high', narrative:'Your burnout is that you may be considered controlling or anal retentive and people with withdraw because that cannot live up to your standards.' },
{ test:'personality', factor:'perfectionist', range:'medium', narrative:'Your burnout is an imbalance with organized or routine sequential environments and chaotic flexible last minute environments.' },
{ test:'personality', factor:'perfectionist', range:'low', narrative:'Your burnout is being caught unprepared, confused and unable to find things when needed.' },
{ test:'personality', factor:'tense', range:'high', narrative:'Your burnout is waiting too long before starting projects and being careless.' },
{ test:'personality', factor:'tense', range:'medium', narrative:'Your burnout is waiting too long to be aware of a project or decision. Procrastination burns you out.' },
{ test:'personality', factor:'tense', range:'low', narrative:'Your burnout being perceived as unmotivated or too slow.' },
{ test:'eji', factor:'aware', range:'high', narrative:'Your burnout is highly rational, logical and factual environments.' },
{ test:'eji', factor:'aware', range:'medium', narrative:'Your burnout is imbalance of rational logic and emotional.' },
{ test:'eji', factor:'aware', range:'low', narrative:'Your burnout is emotional subjective reasoning.' },
{ test:'eji', factor:'identifyown', range:'high', narrative:'Your burnout is environments where people are unable to recognize the difference between similar types' },
{ test:'eji', factor:'identifyown', range:'medium', narrative:'Your burnout is having to distinguish between different types of emotions to often.' },
{ test:'eji', factor:'identifyown', range:'low', narrative:'Your burnout is being put in a position where you have to identify which emotions are.' },
{ test:'eji', factor:'identifyothers', range:'high', narrative:'Your burnout is environments where people cannot distinguish between different types of emotions.' },
{ test:'eji', factor:'identifyothers', range:'low', narrative:'Your burnout is being in the position of having to identify other people&rsquo;s emotions.' },
{ test:'eji', factor:'manageown', range:'high', narrative:'Your burnout is environments where people are reactive.' },
{ test:'eji', factor:'manageown', range:'medium', narrative:'Your burnout is highly reactive environments.' },
{ test:'eji', factor:'manageown', range:'low', narrative:'Your burnout is situations where you have to manage your emotions in stressful situations.' },
{ test:'eji', factor:'manageothers', range:'high', narrative:'Your burnout is being in situations where people stay in a victim consciousness.' },
{ test:'eji', factor:'manageothers', range:'medium', narrative:'Your burnout is situations where people stay in a victim consciousness.' },
{ test:'eji', factor:'manageothers', range:'low', narrative:'Your burnout is having to manage other people&rsquo;s emotions in stressful situations.' },
{ test:'eji', factor:'problemsolving', range:'high', narrative:'Your burnout is being around people who are stuck in negative emotions an unwilling or unable to get out.' },
{ test:'eji', factor:'problemsolving', range:'medium', narrative:'Your burnout is people who are not receptive to changing out of the victim mode.' },
{ test:'eji', factor:'problemsolving', range:'low', narrative:'Your burnout is having to use your emotions and problem solving.' },
{ test:'eji', factor:'express', range:'high', narrative:'Your burnout is being in situations where others are unable to understand your expression or emotions.' },
{ test:'eji', factor:'express', range:'medium', narrative:'Your burnout in situations where you are unable to be heard emotionally.' },
{ test:'eji', factor:'express', range:'low', narrative:'Your burnout is having to express your emotions adaptively in a situation.' },
{ test:'eji', factor:'impression', range:'medium', narrative:'Your burnout is situations where you are unable to represent yourself accurately and be authentic.' },
{ test:'vak', factor:'auditory', range:'high', narrative:'Your burnout is trying to communicate or take in information visually or working with your hands and body too much.' },
{ test:'vak', factor:'visual', range:'high', narrative:'Your burnout is trying to communicate or take in information auditorally or wrorking with your hands and body too much.' },
{ test:'vak', factor:'kinesthetic', range:'high', narrative:'Your burnout is trying to communicate or take in information visually or auditorally without movement and working with your hands.' },
{ test:'vak', factor:'auditory+kinesthetic', range:'high', narrative:'Your burnout is trying to communicate or take in information visually.' },
{ test:'vak', factor:'visual+auditory', range:'high', narrative:'Your burnout is trying to communicate or take in information through your hands and body.' },
{ test:'vak', factor:'visual+kinesthetic', range:'high', narrative:'Your burnout is trying to communicate or take in information auditorally.' },
{ test:'vak', factor:'balanced', range:'high', narrative:'Your burnout is trying to communicate or take in information with too much emphasis on one more than the other, for example all through listening, all through reading or all through your body.' },
{ test:'soi', factor:'CFU', range:'low', narrative:'Your burnout is having to coordinate small objects and notice visual details.' },
{ test:'soi', factor:'CFC', range:'low', narrative:'Your burnout is organizing and classifying..' },
{ test:'soi', factor:'CFS', range:'low', narrative:'Your burnout is dealing with problems, and learning and comprehending spatial relationships' },
{ test:'soi', factor:'CFT', range:'low', narrative:'Your burnout is having to comprehend objects and shapes in space, and spatial relationships when viewed from different angles.' },
{ test:'soi', factor:'CSR', range:'low', narrative:'Your burnout is having to use abstract idea and deal with ambiguity.' },
{ test:'soi', factor:'CSS', range:'low', narrative:'Your burnout is having to do arithmetic tasks requiring concentration.' },
{ test:'soi', factor:'CMU-R', range:'low', narrative:'Your burnout is having to work with verbal ideas. (look at AVK score)' },
{ test:'soi', factor:'CMU-M', range:'low', narrative:'Your burnout is working with conceptual math, algebra, geometry, trigonometry or calculus. .' },
{ test:'soi', factor:'CMR', range:'low', narrative:'Your burnout is being in positions where you have to comprehend and communicate abstract thinking verbally.' },
{ test:'soi', factor:'CMS', range:'low', narrative:'Your burnout is having to use verbal communication.' },
{ test:'soi', factor:'MFU', range:'low', narrative:'Your burnout is having to remember incidental info without concentrating on it.' },
{ test:'soi', factor:'MSUv', range:'low', narrative:'Your burnout is having to visually memorize information.' },
{ test:'soi', factor:'MSSv', range:'low', narrative:'Your burnout is having to recall visual memory out of sequence.' },
{ test:'soi', factor:'MSUa', range:'low', narrative:'Your burnout is having to remember auditory information.' },
{ test:'soi', factor:'MSSa', range:'low', narrative:'Your burnout is having to remember auditory details and work with them in correct order.' },
{ test:'soi', factor:'MSI', range:'low', narrative:'Your burnout is having to maintain attention and remember complex information.' },
{ test:'soi', factor:'MMI', range:'low', narrative:'Your burnout is having to use inferential memory and creativity.' },
{ test:'soi', factor:'EFU', range:'low', narrative:'Your burnout is having to make analytical decisions using discrimination and detailed information.' },
{ test:'soi', factor:'EFC', range:'low', narrative:'Your burnout is having to be organized using spatial relations.' },
{ test:'soi', factor:'ESC', range:'low', narrative:'Your burnout is having to use numerical data, make it into a concept and select appropriate procedures.' },
{ test:'soi', factor:'ESS', range:'low', narrative:'Your burnout is solving problems using data to make judgements and develop a plan.' },
{ test:'soi', factor:'NFU', range:'low', narrative:'Your burnout is having to use hand eye coordination.' },
{ test:'soi', factor:'NSS', range:'low', narrative:'Your burnout is having to use data and apply mathematical facts to it.' },
{ test:'soi', factor:'NST', range:'low', narrative:'Your burnout is having to read rapidly or scan data.' },
{ test:'soi', factor:'NSI', range:'low', narrative:'Your burnout is having to make accurate logical decisions.' },
{ test:'soi', factor:'DFU', range:'low', narrative:'Your burnout is having to work with spatial creative ideas and art.' },
{ test:'soi', factor:'DMU', range:'low', narrative:'Your burnout is having to use creative writing.' },
{ test:'soi', factor:'DSR', range:'low', narrative:'Your burnout is using symbolic relations and math, such as Algebra.' },
];

peg.gifts = [
{ test:'temperament', factor:'extravert', range:'high', narrative:'You have a gift with people and are nourished by being around people. This also means that you get your life energy from being with people.' },
{ test:'temperament', factor:'extravert', range:'medium', narrative:'You have a gift of being nourished by two different sources. You are nourished by one on one or small group conversations, which are deeper in meaning and content, and you are nourished by being with large groups of people, many of whom you may not know, and with a very different depth of communication.' },
{ test:'temperament', factor:'extravert', range:'low', narrative:'You have a gift of working in solitary conditions. You may prefer this or small group conversations that are deeper in meaning. You are nourished by one on one "essence-level communication" to the less personal, more generalized communication that usually accompanies larger group activities.' },
{ test:'temperament', factor:'sensible', range:'high', narrative:'You have a gift of valuing rational thought and your ability to reason. You believe that following the established rules allows you to be clearly guided in your endeavors. You tend to be pragmatic in your approach to things, and have confidence in knowledge, both your own and that of others. You trust wisdom that has been gained by experience.' },
{ test:'temperament', factor:'sensible', range:'medium', narrative:'You have a gift of having an unusual understanding of both Sensible/Practical people and Intuitive/Creative people (the ability to think both ways and speak both languages). You use your intuition and creativity in balanced proportion with your wisdom and knowledge of the past. You are able to think outside the box and can be pragmatic to follow the rules or guidelines.' },
{ test:'temperament', factor:'sensible', range:'low', narrative:'You have a gift of having a high degree of Intuitive/Creative potential in your personality.' },
{ test:'temperament', factor:'thinking', range:'high', narrative:'You have a gift of being a high thinker. This shows that you prefer rational solutions to emotional ones and your solutions must make sense.' },
{ test:'temperament', factor:'thinking', range:'low', narrative:'You have a gift of being empathic and put yourself in other&rsquo;s places easily.' },
{ test:'temperament', factor:'thinking', range:'medium', narrative:'You have a gift of being able to use rational thought, rules, wisdom and experience to guide you, but may temper judgements with some empathy. You may be able to see both some of the rational as well as some of the emotional aspect of situations.' },
{ test:'temperament', factor:'judicious', range:'high', narrative:'You have a gift of being a highly Judicious person who enjoys planning, linear timetables, and doing one project at a time in a step-by-step, concrete/sequential manner. The ability to make contingency plans for just about everything. The ability to compile information and research temperament.' },
{ test:'temperament', factor:'judicious', range:'medium', narrative:'You have a gift of being able to either have a plan or flow with what is and be spontaneous.' },
{ test:'temperament', factor:'judicious', range:'low', narrative:'You have a gift of being able to do more than one thing at a time, be spontaneous and be inclined to see life as an adventure. You may prefer to allow things to happen and enjoy the process.' },
{ test:'motivation', factor:'definitions', range:'high', narrative:'You have a gift of being good at following directions and instructions.' },
{ test:'motivation', factor:'definitions', range:'medium', narrative:'You have a gift of being able to create things with only a percentage of the info needed.' },
{ test:'motivation', factor:'definitions', range:'low', narrative:'You have a gift of being able to have a minimal set of instructions and be able to design a project by yourself.' },
{ test:'motivation', factor:'feelings', range:'high', narrative:'You have a gift of being able to value your feelings, make decisions based on feelings and you have empathy for others.' },
{ test:'motivation', factor:'feelings', range:'medium', narrative:'You have a gift of being almost balanced between your feelings and rational thoughts. You may be able to create things with only a percentage of the info needed.' },
{ test:'motivation', factor:'feelings', range:'low', narrative:'You have a gift being able to be detached from feelings and see the rational thoughts behind them.' },
{ test:'motivation', factor:'efficiency', range:'high', narrative:'You have a gift of preparation and cleanup as well as keeping track of details.' },
{ test:'motivation', factor:'efficiency', range:'medium', narrative:'You have a gift of being able to appreciate the big picture, and you also have a gift of paying attention to details. This is a rare gift.' },
{ test:'motivation', factor:'curiosity', range:'high', narrative:'You have a gift of being open to new information and are energized by learning new things and having new experiences' },
{ test:'motivation', factor:'curiosity', range:'medium', narrative:'You have a gift of being willing to take the middle road and accept the wisdom of those around you and still enjoy learning a moderate amount of new things.' },
{ test:'motivation', factor:'authority', range:'high', narrative:'You have a gift of being a great rule follower. You may feel safe with rules and need to follow/learn from established authorities.' },
{ test:'motivation', factor:'authority', range:'medium', narrative:'You have a gift of being able to learn from both established/professional and those who are not.' },
{ test:'motivation', factor:'resistance', range:'high', narrative:'You have a gift of being independent and a free thinker, unencumbered by rules and what people around you think.' },
{ test:'motivation', factor:'resistance', range:'medium', narrative:'You have a gift of being a free thinker but are balanced with what others think and people around you think.' },
{ test:'motivation', factor:'wariness', range:'high', narrative:'You have a gift of not being taken advantage of or conned easily.' },
{ test:'motivation', factor:'wariness', range:'medium', narrative:'You have a gift of being able to feel comfortable evaluating the evidence a person exhibits in order to determine his or her trustworthiness.' },
{ test:'motivation', factor:'wariness', range:'low', narrative:'You have a gift of being able to see what you perceive to be the good in everybody but may give out too much info and be conned by the wrong people.' },
{ test:'motivation', factor:'tools', range:'high', narrative:'You have a gift of finding enjoyment working with your hands and your body. You may see your body as a finely tuned instrument.' },
{ test:'motivation', factor:'tools', range:'medium', narrative:'You have a gift of being a balance of working with your mind and your body' },
{ test:'motivation', factor:'affection', range:'high', narrative:'You have a gift of being nourished by people being affectionate and accepting of you and complementing you in a positive way' },
{ test:'motivation', factor:'affection', range:'medium', narrative:'You have a gift of being able to take it or leave it personal complements.' },
{ test:'motivation', factor:'acclaim', range:'high', narrative:'You have a gift of being motivated by praise and being recognized for your accomplishments.' },
{ test:'motivation', factor:'acclaim', range:'medium', narrative:'You have a gift of being balanced between internal standards and public recognition.' },
{ test:'motivation', factor:'pressure', range:'high', narrative:'You have a gift of being motivated by timelines and internal pressure.' },
{ test:'motivation', factor:'pressure', range:'medium', narrative:'You have a gift of being moderately motivated by internal pressure.' },
{ test:'motivation', factor:'direct', range:'high', narrative:'You have a gift of being motivated by being a leader and being in charge and making decisions.' },
{ test:'motivation', factor:'direct', range:'medium', narrative:'You have a gift of being a team player, but can be a leader if you have to.' },
{ test:'motivation', factor:'avoidance', range:'high', narrative:'You have a gift of possibly being a peace maker' },
{ test:'motivation', factor:'avoidance', range:'medium', narrative:'You have a gift of being balanced between confrontation when needed and keeping the peace and balance in a situation.' },
{ test:'motivation', factor:'disappointment', range:'medium', narrative:'You have a gift of being balanced between owning up to a conflict and not blaming others.' },
{ test:'zinn', factor:'adventure', range:'high', narrative:'You have a gift of being able to be a self-starter and you may do well working with research or entrepreneurial groups creating out of the box ideas. High scorers like to travel and learn new things and have new experiences. You may be motivated by freedom and adventure vs owning things and comfort of established comforts.' },
{ test:'zinn', factor:'adventure', range:'medium', narrative:'You have a gift of being a balance between an entrepreneur and established traditional customs.' },
{ test:'zinn', factor:'adventure', range:'medium', narrative:'You have a gift of being a balance of adventure freedom and comfort control. You may enjoy living life that has adventure and still have safety of owning things and traditional values.' },
{ test:'zinn', factor:'adventure', range:'low', narrative:'You have a gift of being able to enjoy being part of a cohesive group that follows socially acceptable rules and find safety in savings, possessions and owning things.' },
{ test:'zinn', factor:'personal', range:'high', narrative:'You have a gift of being motivated by praise from peers and connections with people.' },
{ test:'zinn', factor:'personal', range:'medium', narrative:'You have a gift of being moderately motivated by connections with people, recognition by your peers and working to your internal standards.' },
{ test:'zinn', factor:'personal', range:'medium', narrative:'You have a gift of being moderately motivated by directing activities and public acclaim.' },
{ test:'zinn', factor:'personal', range:'low', narrative:'You have a gift of being motivated by leadership and public acclaim.' },
{ test:'pf16global', factor:'extrovert', range:'high', narrative:'You have a gift with people and are nourished by being around people. This also means that you get your life energy from being with people, processing information out loud and being social.' },
{ test:'pf16global', factor:'extrovert', range:'medium', narrative:'You have a gift of being nourished by two different sources. You are nourished by being in one-on-one or small group conversations that are deeper in meaning and content and you are nourished by being with large groups of people, many of whom you may not know, and with a very different depth of communication.' },
{ test:'pf16global', factor:'extrovert', range:'low', narrative:'You have a gift of working in solitary conditions. You are nourished by being in one-on-one or small group conversations that are deeper in meaning. You may prefer this "essence-level communication" to the less personal, more generalized communication that usually accompanies larger group activities.' },
{ test:'pf16global', factor:'independence', range:'high', narrative:'You have a gift of being actively self-determined in your own relationships, thinking and actions. You are able to express your feelings, be forceful when needed and challenge the status quo.' },
{ test:'pf16global', factor:'independence', range:'medium', narrative:'You have a gift of being able to balance agreeableness and flexibility while, at the same time, being actively self-determined in your own thinking and actions. You are able to be flexible. You can be assertive, and yet unassuming. You have a moderate ability to express your feelings, be forceful when needed and challenge the status quo. You are generally confident. You may enjoy taking a leadership role, from time to time.' },
{ test:'pf16global', factor:'independence', range:'low', narrative:'You have a gift of being able to value agreeableness, accommodation and cooperativeness.' },
{ test:'pf16global', factor:'tough', range:'high', narrative:'You have a gift of preferring a well-organized life that is consistent, and trying to avoid ambiguity and confusion whenever possible. You tend to be conservative and cautious, being generally uninterested in artistic matters.' },
{ test:'pf16global', factor:'tough', range:'medium', narrative:'You have a gift of having a balanced orientation to new experiences and change. You are open to change and may enjoy thinking of ways to improve things and experimenting.' },
{ test:'pf16global', factor:'tough', range:'low', narrative:'You have a gift of tending to be open to new ideas and ways of doing things. You tend to be intuitive and imaginative, experimenting and trying new approaches. You are open to change. You enjoy variety.' },
{ test:'pf16global', factor:'selfcontrol', range:'high', narrative:'You have a gift of being strongly self-disciplined; a "take-charge" kind of person. You keep your belongings and surroundings neat and in good order, abhorring clutter. You do things methodically, and try to be as precise as possible. Giving up on a problem does not seem an option. You are likely to go about things in a deliberate way, collecting as much information as possible before making a decision. You are cautious and self-motivated. You enjoy setting and working to achieve goals. You often try to control your temper and feelings.' },
{ test:'pf16global', factor:'selfcontrol', range:'medium', narrative:'You have a gift of being somewhat balanced in your comfort with influencing events and people, versus accommodating them. You may feel moderately driven to succeed.' },
{ test:'pf16global', factor:'selfcontrol', range:'low', narrative:'You have a gift of being unconventional. You may enjoy inventing or discovering new things, within the right context. You enjoy pursuing the untried. You are not motivated by material gains.' },
{ test:'pf16global', factor:'anxiety', range:'medium', narrative:'You have a gift of having a balance between your inner pusher/driver and the flow of life.' },
{ test:'pf16global', factor:'anxiety', range:'low', narrative:'You have a gift of tending to feel comfortable with most of your internal thoughts and feelings, as well as external events. You likely have some effective coping skills that you employ in stressful situations. In high-stress situations you may be able to meet the demands of the situation with a clearer head than those who may be overwhelmed by it. You readily trust others and are not easily overwhelmed or worried. You are relaxed enough to be sensitive to the needs of others. Your tendency is to have patience and confidence that things will work out appropriately in time. Your relaxed attitude helps you to weather the storms that may come with demands put on you by others, and you are able to take constructive criticism. You are likely confident and may even be self-directing or self-starting on projects, feeling little pressure to perform up to specific standards.' },
{ test:'pf16primary', factor:'warm', range:'high', narrative:'You have a gift of being able to willingly give help and comfort to others, being considerate of their feelings. You tend to be caringly involved with people. You are likely to enjoy working with others who share their feelings openly, or in a situation such as an office, where others interact frequently. You are comfortable in situations that require closeness with other people. This warmth is often perceived as socially acceptable.' },
{ test:'pf16primary', factor:'warm', range:'medium', narrative:'You have a gift of being able to be warmly involved with others, and yet to maintain a level of reserve, as needed. You may be attentive to others without being extremely outgoing. Having the ability to balance reserve with warmth, you may be quite effective in emergency type situations in which you need to be attentive to the needs of others, and yet detached enough to take necessary action or to be able to prioritize needs without getting caught in the distress of any one individual.' },
{ test:'pf16primary', factor:'warm', range:'low', narrative:'You have a gift in being quite effective in non-interactional endeavors such as research or other more solitary pursuits and being objective and impersonal.' },
{ test:'pf16primary', factor:'abstract', range:'high', narrative:'You have a gift in tending to see the world in terms of concepts versus things. It also shows us that your gift of seeing the big picture is quite evident here. You have the gift of thinking outside the box. You may be able to generate new ideas from old concepts.' },
{ test:'pf16primary', factor:'abstract', range:'medium', narrative:'You have a gift in being able to think creatively, but may prefer to have some general guidelines or procedural steps available by which to gage your thought process and progress on a project. You are as attentive as most to the information and detail that are given, but may prefer to contemplate other possibilities beyond what has been presented.' },
{ test:'pf16primary', factor:'abstract', range:'low', narrative:'You have a gift in being able to attend to details and prefer to take action, rather than theorize about something. You are likely to maintain focus on and responsiveness to what is immediately necessary.' },
{ test:'pf16primary', factor:'stable', range:'high', narrative:'You have a gift in being able to rationalize emotions. You see yourself as being more able than most people to deal calmly with life&rsquo;s demands. You are highly adaptive to new situations.' },
{ test:'pf16primary', factor:'stable', range:'medium', narrative:'You have a gift in often being able to deal calmly with life&rsquo;s demands, being moderately able to adapt to new situations. You may often remain emotionally stable by rationalizing your feelings.' },
{ test:'pf16primary', factor:'dominant', range:'high', narrative:'You have a gift in being rather self-determined. You are comfortable giving people directions and can be tough and sharp if being polite and pleasant doesn&rsquo;t work. You are assertive and competitive.' },
{ test:'pf16primary', factor:'dominant', range:'medium', narrative:'You have a gift in likely being balanced between cooperative and deferential, and assertive and dominant. That is, you usually work with others by doing your part of a project to the best of your ability, speaking up to offer your own ideas when you feel a better way is needed. You are likely to be somewhat assertive in voicing your ideas or opinions if you see them as being useful. You may speak up or attempt to make changes tactfully rather than through force or pushiness.' },
{ test:'pf16primary', factor:'dominant', range:'low', narrative:'You have a gift in being highly cooperative rather than assertive, this may help you to get along with others. You could be a peace-maker.' },
{ test:'pf16primary', factor:'lively', range:'high', narrative:'You have a gift in tending to be enthusiastic, spontaneous, and enjoy attention. You will do well in stimulating social situations, interacting with friends, and other social events. It also shows that you like to be in the middle of excitement and activity. You are a balance of spontaneous and serious. You are energized from being with others and procession information out loud.' },
{ test:'pf16primary', factor:'lively', range:'medium', narrative:'You have a gift in being enthusiastic about certain matters that are important or interesting to you. You can be moderately spontaneous when talking with others about such matters. You may be considered an influential part of a team for your combined seriousness and enthusiasm.' },
{ test:'pf16primary', factor:'lively', range:'low', narrative:'You have a gift in being more inwardly oriented than social and possibly being considered as mature or intelligent.' },
{ test:'pf16primary', factor:'rule', range:'high', narrative:'You have a gift of being a strict follower of rules, principles, and manners. You emphasize the importance of conforming to regulations, viewing yourself as rule-bound, conscientious, and persevering.' },
{ test:'pf16primary', factor:'rule', range:'medium', narrative:'You have a gift of being able to generally value rules and regulations, though you are not overly bound to the strict adherence of them. You may value the freedom to interpret rule according to those ideas in which you believe.' },
{ test:'pf16primary', factor:'rule', range:'low', narrative:'You have a gift in being able to value freedom to do what is important to you. You desire autonomy and flexibility, and may believe that the ends justify the means. You likely ascribe to values not solely based on conventional mores.' },
{ test:'pf16primary', factor:'bold', range:'high', narrative:'You have a gift of being able to seek to be socially bold in an adventuresome way, and enjoy a high level of attention. You often fit into new groups easily and are comfortable speaking with strangers or addressing large groups.' },
{ test:'pf16primary', factor:'bold', range:'medium', narrative:'You have a gift of being balanced in your need for attention, versus autonomy. You are able to be somewhat influential, but are also able to be accommodating when necessary. You prefer cooperation and you may be assertive (rather than dominating) when necessary. You enjoy a balance of time alone and time with others.' },
{ test:'pf16primary', factor:'bold', range:'low', narrative:'You have a gift of tending to prefer social interaction one-on-one or within a small group. You value time to yourself.' },
{ test:'pf16primary', factor:'sensitive', range:'high', narrative:'You have a gift of being highly sensitive or sentimental, and that you tend to base judgements on personal taste and aesthetic values. You use sensitivity and empathy in making choices and are likely more refined in tastes and interests.' },
{ test:'pf16primary', factor:'sensitive', range:'medium', narrative:'You have a gift of being somewhat balanced in your ability to apply sensitivity and empathy to decisions and situations, and yet focus on what needs to be done without undue sentimentality. You are able to consider both functional and subjective aspects of a situation in order to make decisions.' },
{ test:'pf16primary', factor:'sensitive', range:'low', narrative:'You have a gift of having a tendency, in some situations, to be both objective and utilitarian and understand how things operate or work.' },
{ test:'pf16primary', factor:'vigilant', range:'medium', narrative:'You have a gift of being balanced in your tendency to trust versus being vigilant about others’ motives and intentions. You tend to approach people and situations with hope for fairness and good intentions from others, but with a moderate level of vigilance in order to validate your basic assumptions. You are likely aware that a difference may exist between what people say they’ll do and what they actually do.' },
{ test:'pf16primary', factor:'vigilant', range:'low', narrative:'You have a gift in expecting fair treatment, loyalty and good intentions from others. This tends to be accompanied by a sense of well-being and satisfactory relationships. You are putting out positive energy!' },
{ test:'pf16primary', factor:'abstracted', range:'high', narrative:'You have a gift of being able to use your abstract imagination in artistic ways if you make conscious choices as to how abstractly and imaginatively you portray your ideas. Consciousness is the awareness of choice.' },
{ test:'pf16primary', factor:'abstracted', range:'medium', narrative:'You have a gift of being balanced with regard to your orientation to internal mental processes and practicalities of a situation.' },
{ test:'pf16primary', factor:'abstracted', range:'low', narrative:'You have a gift of being able to focus on your senses, observable data, and objective realities and demands of your environment. You tend to be practical and have a down-to-earth manner.' },
{ test:'pf16primary', factor:'private', range:'medium', narrative:'You have a gift of being balanced between being private or non-disclosing, and being forthright or genuine. You tend to be private, but not necessarily at the expense of developing close relationships. You can be seen as friendly by talking easily with others on a less personal level.' },
{ test:'pf16primary', factor:'private', range:'low', narrative:'You have a gift of being forthright, genuine and self-revealing. You may be received as being authentic.' },
{ test:'pf16primary', factor:'apprehensive', range:'medium', narrative:'You have a gift of being balanced between the tendency to be concerned with the future while feeling secure and confident. You likely have the confidence to move forward in situations.' },
{ test:'pf16primary', factor:'apprehensive', range:'low', narrative:'You have a gift of being highly self-assured. You are confident and self-satisfied. You are not apprehensive or worried about your sense of adequacy. You likely spend little, if any time worrying about people who may dislike you or what you might have done or said, but didn&rsquo;t.' },
{ test:'pf16primary', factor:'open', range:'high', narrative:'You have a gift of being able to enjoy thinking of ways to improve things, and experimenting, but you likely get bored by work that is familiar. Your gift may be that you work well with short projects. You tend to find people interesting if they express different viewpoints. You are likely a high adventure freedom individual.' },
{ test:'pf16primary', factor:'open', range:'medium', narrative:'You have a gift of being balanced between openness to change and comfort with traditional ways of doing things. This shows that you moderately balanced between feeling comfortable applying traditional methods to a situation, but are also open to new, more promising, yet untried approaches.' },
{ test:'pf16primary', factor:'open', range:'low', narrative:'You have a gift of tending to feel most secure and confident in doing things that are familiar and routine.' },
{ test:'pf16primary', factor:'selfreliant', range:'high', narrative:'You have a gift of being self-reliant, enjoy and need time alone, and prefer to make you own decisions. You are able to take action on your own when needed.' },
{ test:'pf16primary', factor:'selfreliant', range:'medium', narrative:'You have a gift of being balanced between wanting to work and be with people vs. wanting to work with things and being alone. This indicates that you may do either one depending on the situation. You have enough autonomy to move forward on a task on your own, asking for help as needed.' },
{ test:'pf16primary', factor:'selfreliant', range:'low', narrative:'You have a gift of being group-oriented and prefer to be around people and do things with others. You enjoy working and planning as a team, playing team sports, or at least having a partner in your activities. You often value or even require consultation with peers before making a decision or taking action. This often puts you in a "collaborative/cooperative" position, which may yield great productivity.' },
{ test:'pf16primary', factor:'perfectionist', range:'high', narrative:'You have a gift of being able to do things right, keep things organized in their proper places, and plan ahead. You are most comfortable in highly organized and predictable situations. You like to keep your materials and surroundings in great shape, have things done just right, and plan ahead. You tend to believe that any job should be done thoroughly, if done at all. However, do recognize that you are a small percentage of the population and may be perceived as overly critical and controlling, and people may not be able to live up to your standards' },
{ test:'pf16primary', factor:'perfectionist', range:'medium', narrative:'You have gift of being balanced between being perfectionistic and being tolerant of disorder. You may tend to put a moderate amount of energy into organizing your space and materials. You may have piles in your space, but know where to find most things or you keep your space open, but sweep miscellaneous things into boxes and drawers to free up your space. You may have a general plan for completing a task, but may modify or adjust the process, as needed. For the most part, you try to be as thorough as is reasonable.' },
{ test:'pf16primary', factor:'perfectionist', range:'low', narrative:'You have a gift of having a high tolerance for disorder. You tend to leave many things to chance, and are able to be comfortable in a disorganized setting. You may say that you don&rsquo;t mind if your space is messy, that you don&rsquo;t always take time to think ahead of everything needed for a job, and that not all jobs need to be done with the same amount of care as others. You are able to work in situations that are less structured, predictable and not highly organized. You feel comfortable with situations that can be approached with a high amount of flexibility and done on the spur-of-the-moment and/or gather info until the last minute. You prefer to act without the need to plan ahead. You may also have the gift of collecting info from seemingly unrelated sources and put them together at the last minute.' },
{ test:'pf16primary', factor:'tense', range:'high', narrative:'You have a gift of possibly being motivated by deadlines and accomplishing things.' },
{ test:'pf16primary', factor:'tense', range:'medium', narrative:'You have a gift in being moderately driven, and yet often well composed, you are likely to be effective in accomplishing tasks and communicating with others in a socially acceptable way. Your moderate level of tolerance for frustration, and if coupled with the appropriate level of communication may lead to positive changes in situations to great benefit.' },
{ test:'pf16primary', factor:'tense', range:'low', narrative:'You have a gift of tending to feel relaxed and tranquil. You are often patient and are slow to frustration. You are not often bothered by interruptions, and don&rsquo;t get as fidgety and restless as many people would when waiting. You are not easily annoyed, and usually regain composure quickly after an emotional upset, but f your score is extremely high, you may be unmotivated or complacent.' },
{ test:'eji', factor:'aware', range:'high', narrative:'You have a gift of being able to honor your own emotions and the emotions of others. You likely devote more of your mental resources than do most people attending to and being conscious of your own and others&rsquo; feelings through both verbal and nonverbal clues.' },
{ test:'eji', factor:'aware', range:'medium', narrative:'You have a gift of being as likely as most people to pay attention to the emotions of your own or others. You probably spend an average amount of time attending to your own and others&rsquo; feelings through verbal and nonverbal cues.' },
{ test:'eji', factor:'aware', range:'low', narrative:'You have a gift of valuing facts and logic, but don’t value emotions.' },
{ test:'eji', factor:'identifyown', range:'high', narrative:'You have a gift of being generally clear about how you feel at any given time. Additionally, you tend not to experience confusion between similar types of emotions such as sadness and disappointment.' },
{ test:'eji', factor:'identifyown', range:'medium', narrative:'You have a gift of being moderately able to evaluate and identify your feelings and to be able to distinguish between combinations of emotions that are similar, such as sadness and disappointment. You are as likely as most people to be clear about how you feel at a given time.' },
{ test:'eji', factor:'identifyothers', range:'high', narrative:'You have a gift of being confident about your assessment of emotions in other people. You have little confusion about the emotions of people around you. You report being able to accurately evaluate the emotions of others, and to distinguish between combinations of feelings or between similar emotions such as sadness and disappointment.' },
{ test:'eji', factor:'identifyothers', range:'medium', narrative:'You have a gift of having an average ability to assess the emotions of other people.' },
{ test:'eji', factor:'manageown', range:'high', narrative:'You have a gift of being able to access, generate, and express appropriate emotions when needed to regulate positive emotions. You also are able to deal with negative or unpleasant emotions. You report having strategies to make yourself feel better after a bad experience. You are able to adjust how you feel more easily than most people. In other words, you are able to construct both positive and negative feelings rather easily in order to alter your mood. In addition, you are likely able to maintain your mood for longer periods of time than most people.' },
{ test:'eji', factor:'manageown', range:'medium', narrative:'You have a gift of having a moderate ability to adjust how you feel to the situation.' },
{ test:'eji', factor:'manageothers', range:'high', narrative:'You have a gift at being skilled at recognizing and influencing how others feel. You may use verbal and nonverbal cues to regulate the mood of others. This may take the form of consoling, influencing or persuading, and generating excitement and enthusiasm in others. You have a tendency toward making other people feel relaxed and comfortable. You are likely to try to cheer people up if you notice that they are in a bad mood.' },
{ test:'eji', factor:'manageothers', range:'medium', narrative:'You have a gift of having an average ability to recognize and influence the way other people feel. You may be moderately successful at consoling, persuading, or generating excitement and enthusiasm.' },
{ test:'eji', factor:'problemsolving', range:'high', narrative:'You have a gift at being skilled at recognizing the effects emotions have on cognitive performance and at applying that knowledge in appropriate situations. For example, you may be able to access creativity through increasing positive moods, or enhance analytical focus by restraining excitement. You are able to identify and incorporate emotional information into everyday tasks involving planning, interpersonal interactions, motivation, decision making, and problem solving. You are likely aware of when and how your emotional experiences influence your performance. You also attempt to create mood states that facilitate the tasks on which you are focused.' },
{ test:'eji', factor:'problemsolving', range:'medium', narrative:'You have a gift of having a moderate ability to recognize the effects emotions have on cognitive performance and applying that knowledge in appropriate situations. For example, you are as able as most people to access creativity through increasing positive moods, or enhance analytical focus by restraining excitement. You may be moderately successful at identifying and incorporating emotional information into everyday tasks involving planning, interpersonal interactions, motivation, decision making, and problem solving. You may sometimes try to create mood states that facilitate the task at hand.' },
{ test:'eji', factor:'express', range:'high', narrative:'You have a gift of being able to adaptively communicate how you feel more often than most people. You are able to let others know how you feel and, when necessary, express your negative reactions to the behavior of others. You are able to express those feelings that facilitate a desired outcome.' },
{ test:'eji', factor:'express', range:'medium', narrative:'You have a gift of having an average ability to adaptively communicate how you feel. You may be moderately successful at letting others know how you feel and, when necessary, express your negative reactions to the behavior of others. Or, perhaps you are able to let people know how you feel, but may have greater difficulty expressing your negative reaction to their behavior. Conversely, you may be able to show your negative reaction to the behavior of others but be less able to express how you feel about it.' },
{ test:'eji', factor:'impression', range:'high', narrative:'You have a gift of being able to represent yourself accurately and accept that you are not perfect.' },
{ test:'eji', factor:'impression', range:'medium', narrative:'You have a gift of being able to likely represent yourself fairly accurately and accept that you are not perfect.' },
{ test:'vak', factor:'auditory', range:'high', narrative:'You have a gift of taking in information through sound and vibration.' },
{ test:'vak', factor:'visual', range:'high', narrative:'You have a gift of taking in information visually.' },
{ test:'vak', factor:'kinesthetic', range:'high', narrative:'You have a gift of taking in information through your body being a tool and experiencing life through touch, sensation and body movement.' },
{ test:'vak', factor:'auditory+kinesthetic', range:'high', narrative:'You have a gift of taking in information through sound/vibration and through Your body, movement and your hands.' },
{ test:'vak', factor:'visual+auditory', range:'high', narrative:'You have a gift of taking in information visually and through sound/vibration.' },
{ test:'vak', factor:'visual+kinesthetic', range:'high', narrative:'You have a gift of taking in information visually and through your body, movement and your hands.' },
{ test:'vak', factor:'balanced', range:'high', narrative:'You have a gift of taking in information through all three avenues at once and integrate them.' },
{ test:'soi', factor:'CFU', range:'high', narrative:'You have a gift of coordinating small objects and visual details without visual stress. (this may enhance your ability in areas such as graphic design, piloting, photography, dentistry, or data entry)' },
{ test:'soi', factor:'CFU', range:'medium', narrative:'You have a gift of having a moderate ability for coordinating small objects and visual details without visual stress.' },
{ test:'soi', factor:'CFC', range:'high', narrative:'You have a gift of easily comprehending and organizing classification schemes and concepts well. (this may enhance your ability in areas such as library science, clerical, filing, or the sciences.)' },
{ test:'soi', factor:'CFC', range:'medium', narrative:'You have a gift of having a moderate ability for comprehending and organizing classification schemes and concepts.' },
{ test:'soi', factor:'CFC', range:'medium', narrative:'You are nourished by a moderate amount of organizing or classifying.' },
{ test:'soi', factor:'CFS', range:'high', narrative:'You have a gift in learning and comprehending spatial systems easily. (this may enhance your ability in areas such as engineering, sciences, computer sciences, or architecture)' },
{ test:'soi', factor:'CFS', range:'medium', narrative:'You have a gift of having a moderate ability for learning and comprehending spatial systems.' },
{ test:'soi', factor:'CFT', range:'high', narrative:'You have a gift of understanding objects in space and shapes from any perspective. (this may enhance your ability in areas such as technology, electronics, science, math, and design.)' },
{ test:'soi', factor:'CFT', range:'medium', narrative:'You have a gift of having a moderate ability for comprehending objects in space and shapes from various perspective.' },
{ test:'soi', factor:'CSR', range:'high', narrative:'You have a gift of making conceptual leaps using abstract relations. Good at details on jobs where there is ambiguity. (this may enhance your ability in areas such as sciences, theoretical interests, or computers.)' },
{ test:'soi', factor:'CSR', range:'medium', narrative:'You have a gift of having a moderate ability for making conceptual leaps using abstract relations. You would likely be average on jobs where there is ambiguity.' },
{ test:'soi', factor:'CSS', range:'high', narrative:'You have a gift of working well with arithmetic and tasks requiring concentration, but become bored with repetitive work. (this may enhance your ability in areas such as accounting, banking, bookkeeping, cashiering, or clerical.)' },
{ test:'soi', factor:'CSS', range:'medium', narrative:'You have a gift of having a moderate ability for working with arithmetic and tasks requiring concentration as long as it is not too repetitive.' },
{ test:'soi', factor:'CMU-R', range:'high', narrative:'You have a gift of communicating and working with verbal ideas. (this may enhance your ability in areas where you process verbal information.)' },
{ test:'soi', factor:'CMU-R', range:'medium', narrative:'You have a gift of having a moderate ability for communicating and working with verbal ideas.' },
{ test:'soi', factor:'CMU-M', range:'high', narrative:'You have a gift of understanding math concepts. (this may enhance your ability in areas using mathematics.)' },
{ test:'soi', factor:'CMU-M', range:'medium', narrative:'You have a gift of having a moderate ability in understanding math concepts.' },
{ test:'soi', factor:'CMR', range:'high', narrative:'You have a gift of rapid comprehension and good communication of ideas and abstract thinking. (this may enhance your ability in areas such as sales, teaching, or public relations.)' },
{ test:'soi', factor:'CMR', range:'medium', narrative:'You have a gift of having a moderate ability for comprehension, and communicating ideas and abstract thinking.' },
{ test:'soi', factor:'CMS', range:'high', narrative:'You have a gift of understanding the syntax of interrelated verbal systems and can follow directions easily. (this may enhance your ability in professions in verbal communication)' },
{ test:'soi', factor:'CMS', range:'medium', narrative:'You have a gift of having a moderate ability for understanding the syntax of interrelated verbal systems and for following directions.' },
{ test:'soi', factor:'MFU', range:'high', narrative:'You have a gift in remembering incidental information when not specifically concentrating on it. (this may enhance your ability in areas such as flying, navigation, printing and layout, nursing, medical lab work, and other detailed work.)' },
{ test:'soi', factor:'MFU', range:'medium', narrative:'You have a gift of having a moderate ability for remembering incidental information when not specifically concentrating on it.' },
{ test:'soi', factor:'MSUv', range:'high', narrative:'You have a gift of attending, concentrating, and recalling information visually. (this may enhance your ability in fields involving notation.)' },
{ test:'soi', factor:'MSUv', range:'medium', narrative:'You have a gift in having a moderate ability for being able to attend, concentrate, and recall information visually.' },
{ test:'soi', factor:'MSSv', range:'high', narrative:'You have a gift of holding information and recalling it in a different sequence visually. (this may enhance your ability in fields involving notation.)' },
{ test:'soi', factor:'MSSv', range:'medium', narrative:'You have a gift in having an average ability for holding information and recalling it in a different sequence visually.' },
{ test:'soi', factor:'MSUa', range:'high', narrative:'You have a gift of attending, concentrating, and recalling information auditorally. Check your AVK test to see how you take in information.' },
{ test:'soi', factor:'MSUa', range:'medium', narrative:'You have a gift of having a moderate ability for being able to attend, concentrate, and recall information auditorally.' },
{ test:'soi', factor:'MSSa', range:'high', narrative:'You have a gift of being able to pay attention to auditory details, hold them in mind while working with them, and keep information in correct order. (this may enhance your ability in a field involving math, music, and verbal instructions.)' },
{ test:'soi', factor:'MSSa', range:'medium', narrative:'You have a gift of having a moderate ability for being able to pay attention to auditory details, hold them in mind while working with them, and keep information in correct order.' },
{ test:'soi', factor:'MSI', range:'high', narrative:'You have a gift of being able to maintain attention, concentrate and associate information on demand.' },
{ test:'soi', factor:'MSI', range:'medium', narrative:'You have a gift of having a moderate ability for attention, concentration, recalling complex information, and associating information.' },
{ test:'soi', factor:'MMI', range:'high', narrative:'You have a gift of having excellent inferential memory will likely allow you to take initiative. (With high CSR and DSR, this may enhance your ability in inventive/creative careers in computers, science, or theoretical science.)' },
{ test:'soi', factor:'MMI', range:'medium', narrative:'You have a gift of having a moderate ability for inferential memory.' },
{ test:'soi', factor:'EFU', range:'high', narrative:'You have a gift of being able to discriminate and make decisions about detailed information. (this may enhance your ability in the fields such as plumbing, welding, nursing, police work, photography, bookkeeping, lab assistants, or data processing.)' },
{ test:'soi', factor:'EFU', range:'medium', narrative:'You have a gift of having a moderate ability for being able to discriminate and make decisions about detailed information.' },
{ test:'soi', factor:'EFC', range:'high', narrative:'You have a gift of being able to be well organized using spatial information. (this may enhance your ability in science, library science, and repair estimating.)' },
{ test:'soi', factor:'EFC', range:'medium', narrative:'You have a gift of having a moderate ability for being organized using spatial information.' },
{ test:'soi', factor:'ESC', range:'high', narrative:'You have a gift of being efficient at conceptualizing numerical data and use good judgment in selecting appropriate procedures. (this may enhance your ability in insurance data, analysts, programmers, and data processing.)' },
{ test:'soi', factor:'ESC', range:'medium', narrative:'You have a gift of having a moderate ability for being able to conceptualize numerical data and selecting appropriate procedures.' },
{ test:'soi', factor:'ESS', range:'high', narrative:'You have a gift of being efficient at solving problems that require judgement and planning in data dependent jobs. You are good at details. (this may enhance your ability in detailed work in a supervisory capacity.)' },
{ test:'soi', factor:'ESS', range:'medium', narrative:'You have a gift of having a moderate ability for solving problems that require judgement and planning in data dependent jobs.' },
{ test:'soi', factor:'NFU', range:'high', narrative:'You have a gift of good eye-hand coordination. (If you have art talent or interest, you may be gifted in drafting, architecture, or fashion illustration.) (look at AVK scores)' },
{ test:'soi', factor:'NFU', range:'medium', narrative:'You have a gift of having a moderate ability in eye-hand coordination.' },
{ test:'soi', factor:'NSS', range:'high', narrative:'You have a gift of having an excellent ability of using data and applying mathematical facts. (this may enhance your ability in sales, data analysis, bookkeeping, banking or stock brokerage)' },
{ test:'soi', factor:'NSS', range:'medium', narrative:'You have a gift of having a moderate ability for using data and applying mathematical facts.' },
{ test:'soi', factor:'NST', range:'high', narrative:'You have a gift of being able to read rapidly or scan data, items, or words. (this may enhance your ability in editing, court reporting, stenography, TV script work, secretarial work, or the Air Force.)' },
{ test:'soi', factor:'NST', range:'medium', narrative:'You have a gift of having a moderate ability to read rapidly or scan data, items, or words.' },
{ test:'soi', factor:'NSI', range:'high', narrative:'You have a gift of having the ability to make accurate decisions which depend on logic. You&rsquo;re able to use good reason and logic in solving problems. (this may enhance your ability in computer programming and administration, supervision, or executive work.)' },
{ test:'soi', factor:'NSI', range:'medium', narrative:'You have a gift of having a moderate ability for making accurate decisions which depend on logic.' },
{ test:'soi', factor:'DFU', range:'high', narrative:'You have a gift of being creative with spatial ideas and you may have art talent. (this may enhance your ability in decorating, architecture, designing, printing and layout.) Please see a connection with kinesthetic test.' },
{ test:'soi', factor:'DFU', range:'medium', narrative:'You have a gift of having an average level of creativity with spatial ideas.' },
{ test:'soi', factor:'DMU', range:'high', narrative:'You have a gift of being creative with word, and you may have writing talent. (this may enhance your ability in sales, psychology, ministry, computer science, journalism, newscasting, or executive positions.)' },
{ test:'soi', factor:'DMU', range:'medium', narrative:'You have a gift of having a moderate ability in your level of creativity with words.' },
{ test:'soi', factor:'DSR', range:'high', narrative:'You have a gift of being able to show creativity in dealing with symbolic relations. (this may enhance your ability in advanced sciences.)' },
{ test:'soi', factor:'DSR', range:'medium', narrative:'You have a gift of having n average ability to deal with symbolic relations such as applying numerical concepts.' },
];

peg.nourishments = [
{ test:'temperament', factor:'extravert', range:'high', narrative:'You are nourished by being with large groups of people.' },
{ test:'temperament', factor:'extravert', range:'medium', narrative:'You are nourished by two different sources. You are nourished by one on one or small group conversations, which are deeper in meaning and content, and you are nourished by being with large groups of people, many of whom you may not know, and with a very different depth of communication' },
{ test:'temperament', factor:'extravert', range:'low', narrative:'You are nourished by spending time alone, or having 1 to 1 conversations with close friends on a more essence level or deeply meaningful conversations' },
{ test:'temperament', factor:'sensible', range:'high', narrative:'You are nourished by being around sensible, practical people and in working with facts and predictable data using concrete solutions.' },
{ test:'temperament', factor:'sensible', range:'medium', narrative:'You are nourished by environments that provide structure and allow for creativity.' },
{ test:'temperament', factor:'sensible', range:'low', narrative:'You are nourished by being around creative people and situations.' },
{ test:'temperament', factor:'thinking', range:'high', narrative:'You are nourished by being around rational, non-emotional people and situations.' },
{ test:'temperament', factor:'thinking', range:'low', narrative:'You are nourished by environments where your feelings are honored.' },
{ test:'temperament', factor:'thinking', range:'medium', narrative:'You are nourished by a balance of emotional support and rational logic.' },
{ test:'temperament', factor:'judicious', range:'high', narrative:'You are nourished by planning, linear timetables and doing one project at a time in step-by-step, concrete sequential manner.' },
{ test:'temperament', factor:'judicious', range:'medium', narrative:'You are nourished by having a balance between planned and unplanned or spontaneous events.' },
{ test:'motivation', factor:'definitions', range:'high', narrative:'You are nourished by knowing what is expected of you and working up to a managers expectations in a highly structured environment.' },
{ test:'motivation', factor:'definitions', range:'medium', narrative:'You are nourished by a combination of knowing what is expected of me and the ability to use my creativity.' },
{ test:'motivation', factor:'definitions', range:'low', narrative:'You are nourished by defined steps and instructions.' },
{ test:'motivation', factor:'feelings', range:'high', narrative:'You are nourished by environments where emotions and empathy are honored.' },
{ test:'motivation', factor:'feelings', range:'medium', narrative:'You are nourished by a balance of rational thought and empathy.' },
{ test:'motivation', factor:'feelings', range:'low', narrative:'You are nourished by environments of rational thought and logic.' },
{ test:'motivation', factor:'efficiency', range:'high', narrative:'You are nourished by being in an organized, sequential environment.' },
{ test:'motivation', factor:'efficiency', range:'medium', narrative:'You are nourished by being in a position where you can see and recognize the big picture of the project.' },
{ test:'motivation', factor:'curiosity', range:'high', narrative:'You are nourished by learning new things and accumulating information and wisdom. You are also nourished by experiencing new things and freedom.' },
{ test:'motivation', factor:'curiosity', range:'medium', narrative:'You are nourished by knowing the established rules and having the ability to think outside the box with creative ideas and experiences.' },
{ test:'motivation', factor:'authority', range:'high', narrative:'You are nourished by learning from people you consider to be experts.' },
{ test:'motivation', factor:'authority', range:'medium', narrative:'You are nourished by knowing what the rules are, but having the flexibility to go outside the rules when needed.' },
{ test:'motivation', factor:'resistance', range:'high', narrative:'You are nourished by not having to conform to society’s absolute rules.' },
{ test:'motivation', factor:'resistance', range:'medium', narrative:'You are nourished by flexibility in society’s rules.' },
{ test:'motivation', factor:'wariness', range:'high', narrative:'You are nourished by being able to keep good boundaries about your personal life.' },
{ test:'motivation', factor:'wariness', range:'medium', narrative:'You are nourished by being able to discern who is safe to expose personal information to and who is not.' },
{ test:'motivation', factor:'wariness', range:'low', narrative:'You are nourished by being around trustworthy people.' },
{ test:'motivation', factor:'tools', range:'high', narrative:'You are nourished by working with your hands, exercising or working with your body in a kinesthetic motion, moving while you are thinking or working.' },
{ test:'motivation', factor:'tools', range:'medium', narrative:'Your nourishment is working with both your hands and your mind.' },
{ test:'motivation', factor:'affection', range:'high', narrative:'You are nourished by being complimented and shown affection for what you do.' },
{ test:'motivation', factor:'affection', range:'medium', narrative:'You are nourished by being balanced between being shown affection and complimented and having your own set of inner standards.' },
{ test:'motivation', factor:'acclaim', range:'high', narrative:'You are nourished by being praised publicly for doing a good job, by the team that you work with and by the people who are superior to you.' },
{ test:'motivation', factor:'acclaim', range:'medium', narrative:'You are nourished by being balanced between your own internal standards and public recognition for your work.' },
{ test:'motivation', factor:'pressure', range:'high', narrative:'You are nourished by being allowed to work to your higher internal standards and/or having a team that pushes your limits.' },
{ test:'motivation', factor:'pressure', range:'medium', narrative:'You are nourished by having enough pressure but not being overwhelmed.' },
{ test:'motivation', factor:'direct', range:'high', narrative:'You are nourished by being in charge of people and making decisions.' },
{ test:'motivation', factor:'direct', range:'medium', narrative:'You are nourished by being in a group and not having to be in the leadership position unless necessary, and having a vote in the outcome.' },
{ test:'motivation', factor:'avoidance', range:'high', narrative:'You are nourished by non-confrontational environments.' },
{ test:'motivation', factor:'avoidance', range:'medium', narrative:'You are nourished by being in moderate confrontational environments.' },
{ test:'motivation', factor:'adventure', range:'high', narrative:'You are nourished by taking on a project with little to no information and creating it yourself or being in the creative/concept stage of a start-up, travel, learning new things and experiences and high independence.' },
{ test:'motivation', factor:'adventure', range:'medium', narrative:'You are nourished by having a balance of tradition and adventure.' },
{ test:'motivation', factor:'adventure', range:'medium', narrative:'You are nourished by a balance of tradition and adventure.' },
{ test:'motivation', factor:'adventure', range:'low', narrative:'You are nourished by being safe, following rules, owning things and being in structured situations.' },
{ test:'motivation', factor:'personal', range:'high', narrative:'You are nourished by being praised and recognized for what you do and what you have accomplished, and low confrontation situations.' },
{ test:'motivation', factor:'personal', range:'medium', narrative:'You are nourished by moderate recognition from peers and balanced by internal standards.' },
{ test:'motivation', factor:'personal', range:'medium', narrative:'You are nourished by moderate public acclaim and being in charge.' },
{ test:'motivation', factor:'personal', range:'low', narrative:'You are nourished by being recognized by your peers and publically for your accomplishments and being in charge.' },
{ test:'personality', factor:'extrovert', range:'high', narrative:'You are nourished by being social interaction.' },
{ test:'personality', factor:'extrovert', range:'medium', narrative:'You are nourished by a balance of being social and being alone or in a one-on-one setting.' },
{ test:'personality', factor:'extrovert', range:'low', narrative:'You are nourished by being alone or working one-on-one and deep connection. Your home is your sanctuary.' },
{ test:'personality', factor:'independence', range:'high', narrative:'You are nourished by being self-motivated in all areas of your life.' },
{ test:'personality', factor:'independence', range:'medium', narrative:'You are nourished by a balance of flexibility and being self-determined.' },
{ test:'personality', factor:'independence', range:'low', narrative:'You are nourished by peaceful easy going situations and persons.' },
{ test:'personality', factor:'tough', range:'high', narrative:'You are nourished by organization, continuity and solid facts and matters.' },
{ test:'personality', factor:'tough', range:'medium', narrative:'You are nourished by change and improving things.' },
{ test:'personality', factor:'tough', range:'low', narrative:'You are nourished by environments of new ideas, new ways of doing things and using your intuition/creativity.' },
{ test:'personality', factor:'selfcontrol', range:'high', narrative:'You are nourished by neat surroundings, well maintained equipment, being precise, self-discipline and Spartan or minimalist environment.' },
{ test:'personality', factor:'selfcontrol', range:'medium', narrative:'You are nourished by a balance between order/discipline and change/creativity.' },
{ test:'personality', factor:'selfcontrol', range:'low', narrative:'You are nourished by inventing new things and procedures, and the unconventional.' },
{ test:'personality', factor:'anxiety', range:'high', narrative:'You are nourished by slowing down and finding the flow of life. Your mind is not the only intelligence. Ask for help from others.' },
{ test:'personality', factor:'anxiety', range:'medium', narrative:'You are nourished by a balance between your inner pusher/driver and the flow of life.' },
{ test:'personality', factor:'anxiety', range:'low', narrative:'You are nourished by environments that flow with what is and has structure.' },
{ test:'personality', factor:'warm', range:'high', narrative:'You nourished by helping others. “Self-care is not selfish.”' },
{ test:'personality', factor:'warm', range:'medium', narrative:'You are nourished by helping others and maintaining your personal wellbeing at the same time. “Self-care is not selfish.”' },
{ test:'personality', factor:'warm', range:'low', narrative:'You are nourished by environments where objectivity is honored.' },
{ test:'personality', factor:'abstract', range:'high', narrative:'You are nourished by conceptual and theoretical thinking and generating new concepts or ideas.' },
{ test:'personality', factor:'abstract', range:'medium', narrative:'You are nourished by a balance between sensible/practical and theoretical thinking.' },
{ test:'personality', factor:'abstract', range:'low', narrative:'You are nourished by sensible/practical solutions, using details and procedures.' },
{ test:'personality', factor:'stable', range:'high', narrative:'You are nourished by environments where you can deal calming with life’s demands.' },
{ test:'personality', factor:'stable', range:'medium', narrative:'You are nourished by a balance between subjective and objective, and logic and emotions.' },
{ test:'personality', factor:'dominant', range:'high', narrative:'You are nourished by being in charge, directing people and project.' },
{ test:'personality', factor:'dominant', range:'medium', narrative:'You are nourished by being in a position of balance between being in charge and being subservient.' },
{ test:'personality', factor:'lively', range:'high', narrative:'You are nourished by meeting and interacting with new people.' },
{ test:'personality', factor:'lively', range:'medium', narrative:'You are nourished by being balanced in inward or internal (introverted) ideas and outward (extroverted) social connections.' },
{ test:'personality', factor:'lively', range:'low', narrative:'You are nourished by being alone and introspective or with a small group of intimate or intellectual friends.' },
{ test:'personality', factor:'rule', range:'high', narrative:'You are nourished by being in highly ordered, well defined situations.' },
{ test:'personality', factor:'rule', range:'medium', narrative:'You are nourished by being in situations of balance between strict rules and spontaneity and creative thinking.' },
{ test:'personality', factor:'rule', range:'low', narrative:'You are nourished by freedom, autonomy and flexibility.' },
{ test:'personality', factor:'bold', range:'high', narrative:'You are nourished by being in highly social situations and meeting and interacting with new people.' },
{ test:'personality', factor:'bold', range:'medium', narrative:'You are nourished by a balance of meeting and interacting with new situations and people, and privacy and autonomy.' },
{ test:'personality', factor:'bold', range:'low', narrative:'You are nourished by one on one, deeper or introspective and intellectual time versus socially shallow interactions.' },
{ test:'personality', factor:'sensitive', range:'high', narrative:'You are nourished by refined tastes, culture and being around “feelers”.' },
{ test:'personality', factor:'sensitive', range:'medium', narrative:'You are nourished by a balance between rational logic and empathy.' },
{ test:'personality', factor:'sensitive', range:'low', narrative:'You are nourished by sensible practical/rational people and objective situations.' },
{ test:'personality', factor:'vigilant', range:'low', narrative:'You are nourished by being around trustworthy people.' },
{ test:'personality', factor:'abstracted', range:'high', narrative:'You are nourished by creative, of the box solutions.' },
{ test:'personality', factor:'abstracted', range:'medium', narrative:'You are nourished by a balance between practical solutions and creative abstract out of the box solutions.' },
{ test:'personality', factor:'abstracted', range:'low', narrative:'You are nourished by practical, grounded, situations, valuing the wisdom of the past and observable data.' },
{ test:'personality', factor:'private', range:'medium', narrative:'You are nourished by a balance of privacy and self-disclosure.' },
{ test:'personality', factor:'private', range:'low', narrative:'You are nourished by authentic people.' },
{ test:'personality', factor:'open', range:'high', narrative:'You are nourished by being in research, improving things and new ideas.' },
{ test:'personality', factor:'open', range:'medium', narrative:'You are nourished by a balance between routine (tried and true way of doing things) and new ideas and things.' },
{ test:'personality', factor:'open', range:'low', narrative:'You are nourished by doing things that are familiar and routine.' },
{ test:'personality', factor:'selfreliant', range:'high', narrative:'You are nourished by self-sufficiency and autonomy.' },
{ test:'personality', factor:'selfreliant', range:'medium', narrative:'You are nourished by a balance of group or team interaction and independent solitary time.' },
{ test:'personality', factor:'selfreliant', range:'low', narrative:'You are nourished by being in a team or group environment or with a partner.' },
{ test:'personality', factor:'perfectionist', range:'high', narrative:'You are nourished by being in highly organized predictable environments.' },
{ test:'personality', factor:'perfectionist', range:'medium', narrative:'You are nourished by a balance between order and flexibility, and doing routine sequential things and seeing the big picture.' },
{ test:'personality', factor:'perfectionist', range:'low', narrative:'You are nourished by the ability of working with non-structured last minute decisions and disorganized settings, and going with the flow and coming up with last minute decisions.' },
{ test:'personality', factor:'tense', range:'high', narrative:'You are nourished by being aware of deadlines in advance.' },
{ test:'personality', factor:'tense', range:'medium', narrative:'You are nourished by being aware of deadlines and being patient, and collecting information along the way to work on more accurate projects and decisions.' },
{ test:'personality', factor:'tense', range:'low', narrative:'You are nourished by being patient and taking in the big picture and you are slow to become frustrated.' },
{ test:'eji', factor:'aware', range:'high', narrative:'You are nourished by environments where emotional/subjective feelings are recognized.' },
{ test:'eji', factor:'aware', range:'medium', narrative:'You are nourished by a balance between rational and emotional.' },
{ test:'eji', factor:'aware', range:'low', narrative:'You are nourished by facts and logic.' },
{ test:'eji', factor:'identifyown', range:'high', narrative:'You are nourished by being clear about your feelings and emotions, and separating similar types of emotions such as sadness and disappointment.' },
{ test:'eji', factor:'identifyown', range:'medium', narrative:'You are nourished by identifying and distinguishing between different types of emotions (for example sadness versus disappointment)' },
{ test:'eji', factor:'identifyothers', range:'high', narrative:'You are nourished by environments where people can distinguish between similar types of emotions.' },
{ test:'eji', factor:'manageown', range:'high', narrative:'You are nourished by responding to what you want versus what you don’t want.' },
{ test:'eji', factor:'manageown', range:'medium', narrative:'You are nourished by environments where you can use emotional intelligence.' },
{ test:'eji', factor:'manageothers', range:'high', narrative:'You are nourished by being able to help people regulate their mood in a positive way.' },
{ test:'eji', factor:'manageothers', range:'medium', narrative:'You are nourished by helping people regulate their moods.' },
{ test:'eji', factor:'problemsolving', range:'high', narrative:'You are nourished by helping others with changing negative moods to positive and inspiring moods, and motivating them to change.' },
{ test:'eji', factor:'problemsolving', range:'medium', narrative:'You are nourished by helping others to change negative moods to positive, and inspiring and motivating them.' },
{ test:'eji', factor:'express', range:'high', narrative:'You are nourished by being in situations where you are able to use emotions adaptively to let others know how you feel.' },
{ test:'eji', factor:'express', range:'medium', narrative:'You are nourished by people being able to hear you communicate what you are feeling.' },
{ test:'eji', factor:'impression', range:'high', narrative:'You are nourished by situations where you are able to represent yourself accurately, be authentic and not have be perfect.' },
{ test:'eji', factor:'impression', range:'medium', narrative:'You are nourished by situations where you are able to represent yourself accurately, authentically and not have to be perfect.' },
{ test:'vak', factor:'auditory', range:'high', narrative:'You are nourished by stillness, soothing sound, and by taking in information by listening.' },
{ test:'vak', factor:'visual', range:'high', narrative:'You are nourished by visual spacial relations, reading, and taking in your world visually.' },
{ test:'vak', factor:'kinesthetic', range:'high', narrative:'You are nourished by movement, using your body as a tool and working with your hands.' },
{ test:'vak', factor:'auditory+kinesthetic', range:'high', narrative:'You are nourished by stillness, soothing sound, and by taking in information by listening along with movement, using your body as a tool and working with your hands.' },
{ test:'vak', factor:'visual+auditory', range:'high', narrative:'You are nourished by visual spacial relations, reading, and taking in your world visually along with stillness, soothing sound, and by taking in information by listening.' },
{ test:'vak', factor:'visual+kinesthetic', range:'high', narrative:'You are nourished by visual spacial relations, reading, and taking in your world visually along with movement, using your body as a tool and working with your hands.' },
{ test:'vak', factor:'balanced', range:'high', narrative:'You are nourished by a balance of all three avenues at once, stillness, soothing sounds, visual spacial relations, reading, and using your body.' },
{ test:'soi', factor:'CFC', range:'high', narrative:'You are nourished by organizing or classifying.' },
{ test:'soi', factor:'CFS', range:'high', narrative:'You are nourished by learning and comprehending special systems.' },
{ test:'soi', factor:'CFT', range:'high', narrative:'You are nourished by working with objects and shapes in special relations.' },
{ test:'soi', factor:'CSR', range:'high', narrative:'You are nourished by environments using abstract relations to solve ambiguity.' },
{ test:'soi', factor:'CSS', range:'high', narrative:'You are nourished by working on arithmetic tasks requiring concentrations, as long as it is not too repetitive or boring.' },
{ test:'soi', factor:'CMU-R', range:'high', narrative:'You are nourished by communicating and working with verbal ideas.' },
{ test:'soi', factor:'CMU-R', range:'medium', narrative:'You are nourished by public speaking or communicating verbal ideas.' },
{ test:'soi', factor:'CMU-M', range:'high', narrative:'You are nourished by working with mathematical concepts.' },
{ test:'soi', factor:'CMR', range:'high', narrative:'You are nourished by working with rapid comprehension and communication of ideas and abstract ideas.' },
{ test:'soi', factor:'CMS', range:'high', narrative:'You are nourished in environments using syntax of interrelated verbal systems and following directions.' },
{ test:'soi', factor:'MFU', range:'high', narrative:'You are nourished by situations, where you can remember incidental details, and as a result be honored for paid for this skill.' },
{ test:'soi', factor:'MSUv', range:'high', narrative:'You are nourished by being recognized or paid for recalling visual information.' },
{ test:'soi', factor:'MSUv', range:'medium', narrative:'You are nourished by concentrating on and recalling information visually.' },
{ test:'soi', factor:'MSSv', range:'high', narrative:'You are nourished by using visual recall of information in different sequences.' },
{ test:'soi', factor:'MSUa', range:'high', narrative:'You are nourished by situations where you are using auditory memory (the art of active listening).' },
{ test:'soi', factor:'MSSa', range:'high', narrative:'You are nourished by working with auditory memory and details.' },
{ test:'soi', factor:'MSSa', range:'medium', narrative:'You are nourished by situations where you have to remember auditory information in order.' },
{ test:'soi', factor:'MSI', range:'high', narrative:'You are nourished by being in situations of concentration, attention and association of complex information on demand.' },
{ test:'soi', factor:'MMI', range:'high', narrative:'You are nourished by using inferential memory and taking initiative or action in theoretical science or computers.' },
{ test:'soi', factor:'EFU', range:'high', narrative:'You are nourished by being in situations where you are able to use analytical reasoning, discrimination and make decisions about detailed information.' },
{ test:'soi', factor:'EFC', range:'high', narrative:'You are nourished by situations where you organize using visual spatial relations.' },
{ test:'soi', factor:'ESC', range:'high', narrative:'You are nourished by situations where you use numerical concepts, and select and apply procedures based on this.' },
{ test:'soi', factor:'ESS', range:'high', narrative:'You are nourished in situations that require planning and judgement using data.' },
{ test:'soi', factor:'NFU', range:'high', narrative:'You are nourished in situations where good hand eye coordination is needed.' },
{ test:'soi', factor:'NSS', range:'high', narrative:'You are nourished in situations using data and applying mathematical facts or procedures.' },
{ test:'soi', factor:'NST', range:'high', narrative:'You are nourished in situations where you scan data or words and read rapidly.' },
{ test:'soi', factor:'NSI', range:'high', narrative:'You are nourished by situations using accurate decisions, logic and objective data.' },
{ test:'soi', factor:'DFU', range:'high', narrative:'You are nourished in situations using creative spatial ideas and art.' },
{ test:'soi', factor:'DMU', range:'high', narrative:'You are nourished by creative writing and journalism.' },
{ test:'soi', factor:'DSR', range:'high', narrative:'You are nourished by showing creativity with symbolic relations.' },
];
